all: instruction_timing

instruction_timing: instruction_timing.c
	gcc instruction_timing.c -Os -Wall -o instruction_timing

solution: solution.c
	gcc solution.c -Os -Wall -o solution

clean:
	rm -f instruction_timing solution
